openapi: 3.0.3
info:
  title: Credential Services Pengguna API
  version: 1.0.0
  description: >
    Dokumentasi API untuk fitur credential pengguna seperti update password, 
    validasi OTP/PIN, membuat dan update PIN.
    Semua response menggunakan `ResponseForm`.

servers:
  - url: http://localhost:8080
    description: Development Server

components:
  schemas:

    # ====================================================
    # IDENTITAS PENGGUNA
    # ====================================================
    IdentityPengguna:
      type: object
      properties:
        id_pengguna:
          type: integer
          example: 001
        username_pengguna:
          type: string
          example: "username_burung"
        email_pengguna:
          type: string
          example: "burungapp@gmail.com"
      required:
        - id_pengguna
        - username_pengguna
        - email_pengguna

    # ====================================================
    # UNIVERSAL RESPONSE WRAPPER
    # ====================================================
    ResponseForm:
      type: object
      properties:
        status:
          type: integer
          example: 200
        service:
          type: string
          example: "credential_pengguna"
        pesan:
          type: string
          example: "Berhasil"
        response_payload:
          type: object
          nullable: true

    # ====================================================
    # PAYLOAD 1 - Pre Ubah Password Pengguna
    # ====================================================
    PayloadPreUbahPasswordPengguna:
      type: object
      properties:
        identitas_pengguna:
          $ref: "#/components/schemas/IdentityPengguna"
        password_sebelum_user:
          type: string
          format: password
          example: "OldPassword123!"
        password_baru_user:
          type: string
          format: password
          example: "NewPassword456!"
        faktor_kedua_ganti_password_user:
          type: string
          example: "otp"
          description: "Metode verifikasi (otp/pin)"
      required:
        - identitas_pengguna
        - password_sebelum_user
        - password_baru_user
        - faktor_kedua_ganti_password_user

    # ====================================================
    # PAYLOAD 2 - Validate OTP Password Pengguna
    # ====================================================
    PayloadValidateOTPPasswordPengguna:
      type: object
      properties:
        id_pengguna:
          type: integer
          format: int64
          example: 001
        otp_key_ubah_password:
          type: string
          example: "123456"
      required:
        - id_pengguna
        - otp_key_ubah_password

    # ====================================================
    # PAYLOAD 3 - Validate PIN Password Pengguna
    # ====================================================
    PayloadValidatePinPasswordPengguna:
      type: object
      properties:
        id_pengguna:
          type: integer
          format: int64
          example: 001
        pin_key_ubah_password:
          type: string
          format: password
          example: "123456"
      required:
        - id_pengguna
        - pin_key_ubah_password

    # ====================================================
    # PAYLOAD 4 - Membuat PIN Pengguna
    # ====================================================
    PayloadMembuatPinPengguna:
      type: object
      properties:
        identitas_pengguna:
          $ref: "#/components/schemas/IdentityPengguna"
        password_user_membuat_pin:
          type: string
          format: password
          example: "MyPassword123!"
        pin_user_membuat_pin:
          type: string
          format: password
          example: "123456"
          description: "PIN 6 digit"
      required:
        - identitas_pengguna
        - password_user_membuat_pin
        - pin_user_membuat_pin

    # ====================================================
    # PAYLOAD 5 - Update PIN Pengguna
    # ====================================================
    PayloadUpdatePinPengguna:
      type: object
      properties:
        identitas_pengguna:
          $ref: "#/components/schemas/IdentityPengguna"
        pin_baru_update_pin:
          type: string
          format: password
          example: "654321"
          description: "PIN baru 6 digit"
        pin_lama_update_pin:
          type: string
          format: password
          example: "123456"
          description: "PIN lama 6 digit"
      required:
        - identitas_pengguna
        - pin_baru_update_pin
        - pin_lama_update_pin

paths:

  # =====================================================
  # 1. Update Password Pengguna
  # =====================================================
  /user/credential/update-password:
    patch:
      summary: Memulai proses update password pengguna
      description: >
        Endpoint untuk memulai proses perubahan password. 
        Setelah endpoint ini dipanggil, pengguna perlu memvalidasi 
        dengan OTP atau PIN melalui endpoint validasi.
      tags:
        - Credential Pengguna - Password
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PayloadPreUbahPasswordPengguna"
      responses:
        "200":
          description: Berhasil memulai proses update password
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ResponseForm"

  # =====================================================
  # 2. Validate OTP untuk Update Password
  # =====================================================
  /user/credential/validate-password-otp:
    patch:
      summary: Validasi OTP untuk konfirmasi update password
      description: >
        Endpoint untuk memvalidasi kode OTP yang dikirimkan 
        ke pengguna setelah request update password.
      tags:
        - Credential Pengguna - Password
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PayloadValidateOTPPasswordPengguna"
      responses:
        "200":
          description: Berhasil validasi OTP dan update password
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ResponseForm"

  # =====================================================
  # 3. Validate PIN untuk Update Password
  # =====================================================
  /user/credential/validate-password-pin:
    patch:
      summary: Validasi PIN untuk konfirmasi update password
      description: >
        Endpoint untuk memvalidasi PIN pengguna 
        sebagai konfirmasi update password.
      tags:
        - Credential Pengguna - Password
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PayloadValidatePinPasswordPengguna"
      responses:
        "200":
          description: Berhasil validasi PIN dan update password
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ResponseForm"

  # =====================================================
  # 4. Membuat PIN Pengguna
  # =====================================================
  /user/credential/membuat-pin:
    post:
      summary: Membuat PIN baru untuk pengguna
      description: >
        Endpoint untuk membuat PIN pertama kali. 
        Memerlukan password untuk verifikasi identitas.
      tags:
        - Credential Pengguna - PIN
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PayloadMembuatPinPengguna"
      responses:
        "200":
          description: Berhasil membuat PIN
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ResponseForm"

  # =====================================================
  # 5. Update PIN Pengguna
  # =====================================================
  /user/credential/update-pin:
    patch:
      summary: Mengupdate PIN pengguna yang sudah ada
      description: >
        Endpoint untuk mengubah PIN pengguna. 
        Memerlukan PIN lama untuk verifikasi.
      tags:
        - Credential Pengguna - PIN
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PayloadUpdatePinPengguna"
      responses:
        "200":
          description: Berhasil update PIN
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ResponseForm"