package alamat_enums

const (
	Jakarta          = "jakarta"
	Bogor            = "bogor"
	Depok            = "depok"
	Bekasi           = "bekasi"
	Cimahi           = "cimahi"
	Bandung          = "bandung"
	Tasikmalaya      = "tasikmalaya"
	Banjar           = "banjar"
	Cirebon          = "cirebon"
	Sukabumi         = "sukabumi"
	Semarang         = "semarang"
	Surakarta        = "surakarta"
	Salatiga         = "salatiga"
	Magelang         = "magelang"
	Pekalongan       = "pekalongan"
	Tegal            = "tegal"
	Yogyakarta       = "yogyakarta"
	Surabaya         = "surabaya"
	Malang           = "malang"
	Batu             = "batu"
	Madiun           = "madiun"
	Kediri           = "kediri"
	Blitar           = "blitar"
	Probolinggo      = "probolinggo"
	Pasuruan         = "pasuruan"
	Mojokerto        = "mojokerto"
	Serang           = "serang"
	Cilegon          = "cilegon"
	Tangerang        = "tangerang"
	TangerangSelatan = "tangerang selatan"
)
